# Generated by Django 2.0.5 on 2018-08-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=10)),
                ('identificacion', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('telefono', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('abreviacion', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.ManyToManyField(to='personas.Rol'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.TipoIdentificacion'),
        ),
    ]
