# Generated by Django 2.0.5 on 2018-08-24 16:11

import apps.personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20180824_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.ManyToManyField(default=apps.personas.models.get_default_rol, to='personas.Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
