# Generated by Django 2.0.5 on 2018-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20180824_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.ManyToManyField(to='personas.Rol'),
        ),
    ]
