# Generated by Django 2.0.5 on 2018-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.BooleanField(default=True)),
                ('valor', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.Nomina')),
            ],
        ),
    ]
